baseurl = "http://www.turnersale.us"
title = "Turner Sale"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Turner Sale"
    description = "Turner Sale's personal website"
    keywords = "developer,personal,data science, data scientist"
    info = "Junior Data Scientist"
    avatarurl = "images/personal_close.jpg"
    #gravatar = "turner.sale@gmail.com"

    dateformat = "October 19, 2020"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/turnersale"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "www.linkedin.com/in/turner-sale-71b8b0ba"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium"
    weight = 5
    url = "https://medium.com/@johndoe"



[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Projects"
weight = 3
url = "projects/"
